### ISSUE TITLE
JITO mempool closed in 2024

### ISSUE THREAD

**Issue by tech-soundpickr** [weeaa/jito-go#10]
Hi, I've seen the repo offers functionality to "[Subscribe to Mempool Transactions | Accounts], but I noticed this feature was closed due to sandwitch attacks suffered in solana.
If I am correct thi could be removed.
Thanks for your work !

**Comment by weeaa** [comment]
Hi there, the mempool could be re-enabled later at some point by the team hence why you can still call it in jito-go (the function returns an error anyways).
