### ISSUE TITLE
Unable to intialize new no auth client

### ISSUE THREAD

**Issue by ssbanjo** [weeaa/jito-go#13]
I am working on both local machine and on a windows 10 VPS.

For some reason, when tryin to initialize the client on the VPS i get the following error: `rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp [::1]:443: connectex: No connection could be made because the target machine actively refused it.`

this is how my client is being initialized:

```
client, err := searcher_client.NewNoAuth(
   ctx,
   block_engine_url,
   rpc_helper.New(jito_rpc),
   rpc_helper.New(sol_rpc),
   nil,
)
```

Im on MacOS arm64.
A friend of mine is running on his local Windows 10 machine and is getting the same error aswell so I guess it's not only limited to VPS as I think.

**Comment by ssbanjo** [comment]
my friend is running on a windows 11 btw, not windows 10

**Comment by weeaa** [comment]
you might want to look at https://www.reddit.com/r/golang/s/xHKznNqESL

**Comment by ssbanjo** [comment]
but this issue has nothing to do with docker no? i followed your link and all solutions they give are based on docker

**Comment by weeaa** [comment]
did NoAuth func work on ur mac?

**Comment by weeaa** [comment]
can I close or did u not figure it out
