### ISSUE TITLE
Bundles sending, but confirmation not recieved.

### ISSUE THREAD

**Issue by popfendi** [weeaa/jito-go#14]
I'm sending bundles successfuly with:

```
func SendBundle(ctx context.Context, txs []*solana.Transaction) (*jito_pb.SendBundleResponse, error) {
	logger.Sugar.Info("Sending Bundle...")
	if len(txs) > 5 {
		return nil, fmt.Errorf("TX bundle must have len <= 5")
	}
	return client.JITO_CLIENT.BroadcastBundleWithConfirmation(ctx, txs)	
}
```

However the confirmation response isn't received

```
      res, err := executor.SendBundle(context.Background(), []*solana.Transaction{tx})
      if err != nil {
        logger.Sugar.Fatal(err)
      }

      logger.Sugar.Info(res)
```

My code hangs here, but i can see the successful TX on solscan / jito explorer.

**Comment by weeaa** [comment]
hey can u dm @weeaa on Discord, would need more info

**Comment by captainyugi00** [comment]
Having same issue. I am using NoAuth method to create a new client but when sending bundle the code hangs on waiting for the bundle result. Although the bundle is correctly processed if I check the transactions' signatures.

**Comment by popfendi** [comment]
Seems to be an issue with the jito endpoint it's self, I have a fix where I poll for a result using the http endpoint. Will create a PR when I'm back from holiday if there's no other fix for this.

**Comment by weeaa** [comment]
please try the new BroadcastBundleWithConfirmation and lmk if u face issues

**Comment by weeaa** [comment]
bumping @popfendi @captainyugi00 🫡

**Comment by popfendi** [comment]
Just tested this again.

Seems to be working as expected, just to make sure I'm getting the behaviour correct. If the status of the bundle == "Landed", it returns the bundle ID, if it fails or times out it will throw an Error?

**Comment by weeaa** [comment]
yup, i've slightly changed the code to match with bundle id so it should have the expected behavior

**Comment by pymongo** [comment]
> please try the new BroadcastBundleWithConfirmation and lmk if u face issues (http method)

I am using BroadcastBundleWithConfirmation to swap in raydium but signature do not confirm in solana chain

```
16:16:11.192280 raydium.go:266: true 1.0010*0.000999=0.001004
(*jito_pb.SendBundleResponse)(0xc0030d8b40)(uuid:"b321004c8b5fec0c0e74f56d0a537f9ceed311aafe7e84504b2a5a47f196d34d")
16:16:16.198633 raydium.go:348: 5005ms slot=291950879 bundle simulation failure on tx 63mswExmiNLomGEeT5EfiW6zrW8thhFHh1sQWgUczSRN5SRx6gZSxYRMdtVRU4M55fxUY5W3whRmvFNysDZ6gqps, message: A transaction in the bundle failed to execute: [signature=63mswExmiNLomGEeT5EfiW6zrW8thhFHh1sQWgUczSRN5SRx6gZSxYRMdtVRU4M55fxUY5W3whRmvFNysDZ6gqps, error=Blockhash not found]
```

**Comment by weeaa** [comment]
dm weeaa on discord so i can debug
