### ISSUE TITLE
tip stream crash

### ISSUE THREAD

**Issue by iamrekas** [weeaa/jito-go#20]
https://github.com/weeaa/jito-go/blob/6e56f79012f207f270287bd77ca9864d64246301/pkg/util.go#L65

if stream doesn't respond with error but response with empty data, then go thread will panic and entire code just crash. it must have check for size of slice before it's usage.

**Comment by weeaa** [comment]
olup lemme fix that rq

**Comment by weeaa** [comment]
now sends the array directly to the chan, update to latest please.
