### ISSUE TITLE
I tried to transfer money using this library and returned an error

### ISSUE THREAD

**Issue by taotaolin** [weeaa/jito-go#5]
in `searcher.go`
```
if err = c.handleBundleResult(bundleResult); err != nil {
				return nil, err
			}

			var statuses *rpc.GetSignatureStatusesResult
			statuses, err = c.RpcConn.GetSignatureStatuses(ctx, false, bundleSignatures...)
			if err != nil {
				return nil, err
			}

			for _, status := range statuses.Value {
				if status.ConfirmationStatus != rpc.ConfirmationStatusProcessed {
					return nil, errors.New("searcher service did not provide bundle status in time")
				}
			}
```

I tested the transfer operation using the `Send Bundle` method in the example, but returned an error
```
Panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc000000 5 code=0x0 addr=0x0 pc=0x172496e]
```
After inspection, it was found that the `status.Value` may be `nil` or `rpc.ConfirmationStatusConfirmed` an error in my call. resulting in the returned resp being `nil`，How can I obtain the tx_hash for this transaction

**Comment by weeaa** [comment]
hey @taotaolin, do you have Discord? I'd need a few more details, you can contact me over @weeaa on Discord.

**Comment by taotaolin** [comment]
> @weeaa

I contacted you

**Comment by weeaa** [comment]
closed due to [pr](https://github.com/weeaa/jito-go/pull/6)
